name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-format:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
        pipenv-version: [ "v2024.1.0" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code ğŸ‘Œ
        uses: actions/checkout@v4

      - name: Install Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pipenv ${{ matrix.pipenv-version }} ğŸ“¦
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Cache Pipenv ğŸš€
        id: cache-pipenv
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies ğŸ“¦
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --deploy --dev

      - name: Check code formatting ğŸ¨
        run: |
          pipenv run yapf --diff --recursive addons
